#ifndef AV_CALL_FUNCTION_H
#define AV_CALL_FUNCTION_H

#include "php.h"

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AV_call, 0, 2, IS_MIXED, 0)
    ZEND_ARG_TYPE_MASK(0, function, MAY_BE_STRING|MAY_BE_CALLABLE, NULL)
    ZEND_ARG_TYPE_INFO(0, params, IS_ARRAY, 0)
    ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, dependencies, IS_ARRAY, 0, "[]")
ZEND_END_ARG_INFO()

ZEND_FUNCTION(call);

#endif /* AV_CALL_FUNCTION_H */
